### ISSUE TITLE
One plate version stability improvement

### ISSUE THREAD

**Issue by josefprusa** [josefprusa/Prusa3#2]
We need to find out how  to make the connection between the base plate and bottom Y axis threaded rods more sturdy. Well, its good enough, but the bottom threaded rods do bend. That needs to be improved. Of course @kliment 's boxy version doesnt have that, but It isnt visually appealing, which is important these days.

I can think of something like making one of the threaded rods on Y axis longer to left side, add a bar-clamp on that which would hold threaded rod connected somewhere at the top of base plate.

**Comment by CaptainChemist** [comment]
is the piece you are mentioning just in the prusa i3 mini build? I see a strange metal piece in the .dxf file for the i3 mini but not the i3 regular. If that is the piece, is there a source for the full sized piece?
