### ISSUE TITLE
x-ends are mirrored

### ISSUE THREAD

**Issue by foulowl** [josefprusa/Prusa3#94]
From complete-printer.scad: (correct)
http://i.imgur.com/uO5GQ6A.png

From output folder: (incorrect)
http://i.imgur.com/SSK80aW.png

Solution: mirror x-end across x axis.

**Comment by jglauche** [comment]
They actually print like this in the output folder. You turn them around. The open side of the bearings faces the frame. I think the complete-printer.scad is outdated.

**Comment by foulowl** [comment]
Ah, well it needs to be fixed either way, since it's internally inconsistent. 

Is there a picture of the correct orientation?

Thank you!

**Comment by jglauche** [comment]
http://ext01.reprapsource.com/reprapsource-Prusa-i3-Kit-Build-Manual/Prev/IMG_0627.JPG

**Comment by AxTheB** [comment]
Readme in box_frame says "Using doc/complete-printer-plus.scad as a visual clue and doc/manual.txt as a guide, build the printer." and in the orientation in doc/complete-printer-plus.scad is correct iirc.
