### ISSUE TITLE
Firmware Upgrade Requests

### ISSUE THREAD

**Issue by Autoextrude** [josefprusa/Prusa3#98]
1. Automatically Rise nozzle out of the way on the z-axis away from the bed after a print is done 
2. No need to preheat for filament loading. Just choose load filament, it asks you what material to preheat for and it loads. 
3. For unloading filament, it remembers what filament you asked it to preheat for loading and it unloads
4. Scrolling titles for SD Files 
5. Loading filament should have a pre-determined length of filament it should dump for purging the old filament. Not keep asking me 2-3 times if the new color has come out before it even has.  
6. Filament should retract after it’s been loaded. Not let the nozzle stay hot and keep dripping. 
7. Filament should  be retracted during a preheat and not leak out the whole time unless I move the extruder for extruding 
8. Filament should retract at the end of print and not leak on the bed .2mm away where it gets stuck and then it’s difficult to pull the PEI Spring Steel sheet out. 
9. When loading filament, the nozzle should rise in the Z-axis, so when it begins to purge the filament, you can grab the excess and dispose of it. Right now, it does it right against the bed.

**Comment by edef1c** [comment]
This repository doesn't provide or deal with the electronics, let alone firmware. You might want to direct these requests at whoever provides your firmware and/or electronics.
